basePath: /v1
definitions:
  main.Auth:
    properties:
      created_at:
        type: string
      expires_at:
        type: integer
      id:
        type: integer
      token:
        type: string
      updated_at:
        type: string
      user:
        $ref: '#/definitions/main.User'
        type: object
      user_id:
        type: integer
    type: object
  main.GenericResponse:
    properties:
      error:
        type: string
      success:
        type: boolean
    type: object
  main.Unit:
    properties:
      created_at:
        type: string
      editor_type:
        type: string
      file_name:
        type: string
      id:
        type: integer
      loc_deleted:
        type: integer
      loc_written:
        type: integer
      os:
        type: string
      project_name:
        type: string
      started_at:
        type: string
      stopped_at:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  main.User:
    properties:
      created_at:
        type: string
      editor_token:
        type: string
      email:
        type: string
      id:
        type: integer
      name:
        type: string
      units:
        items:
          $ref: '#/definitions/main.Unit'
        type: array
      updated_at:
        type: string
    required:
    - email
    - name
    type: object
  main.VersionResponse:
    properties:
      download:
        example: https://github.com/Hackerlog/core/releases/download/v0.5/core_0.5_windows_amd64.zip
        type: string
      latest:
        example: false
        type: boolean
    type: object
info:
  contact:
    email: deric.cain@gmail.com
    name: Deric Cain
  description: This is the Hackerlog API
  license: {}
  title: Hackerlog API
  version: v0.1
paths:
  /core/version:
    get:
      consumes:
      - application/json
      description: This endpoint takes a few parameters and with those parameters,
        it looks to see if
      parameters:
      - description: X-Hackerlog-EditorToken
        in: header
        name: X-Hackerlog-EditorToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.VersionResponse'
            type: object
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Returns a link of the latest version of the Core app
      tags:
      - core
  /mailing-list:
    post:
      consumes:
      - application/json
      description: This adds a user to the mailing list
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.GenericResponse'
            type: object
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Adds a user to the mailing list
      tags:
      - mailing-list
  /units:
    get:
      consumes:
      - application/json
      description: This gets all of the units of work for a specific user. The user
        is identified by the
      parameters:
      - description: X-Hackerlog-EditorToken
        in: header
        name: X-Hackerlog-EditorToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Unit'
            type: array
      summary: Gets units of work for a user
      tags:
      - units
  /users/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT on successful login
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Auth'
            type: object
        "401":
          description: Unauthorized
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Authenticates a user
      tags:
      - auth
swagger: "2.0"
