basePath: /v1
definitions:
  main.Unit:
    properties:
      created_at:
        type: string
      editor_type:
        type: string
      file_name:
        type: string
      id:
        type: integer
      loc_deleted:
        type: integer
      loc_written:
        type: integer
      os:
        type: string
      project_name:
        type: string
      started_at:
        type: string
      stopped_at:
        type: string
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  main.VersionResponse:
    properties:
      download:
        example: https://github.com/Hackerlog/core/releases/download/v0.5/core_0.5_windows_amd64.zip
        type: string
      latest:
        example: false
        type: boolean
    type: object
info:
  contact:
    email: deric.cain@gmail.com
    name: Deric Cain
  description: This is the Hackerlog API
  license: {}
  title: Hackerlog API
  version: v0.1
paths:
  /core/version:
    get:
      consumes:
      - application/json
      description: This endpoint takes a few parameters and with those parameters,
        it looks to see if
      parameters:
      - description: X-Hackerlog-EditorToken
        in: header
        name: X-Hackerlog-EditorToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.VersionResponse'
            type: object
        "400":
          description: Bad request
          schema:
            type: string
        "401":
          description: Unauthorized
          schema:
            type: string
      summary: Returns a link of the latest version of the Core app
      tags:
      - core
  /units:
    get:
      consumes:
      - application/json
      description: This gets all of the units of work for a specific user. The user
        is identified by the
      parameters:
      - description: X-Hackerlog-EditorToken
        in: header
        name: X-Hackerlog-EditorToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Unit'
            type: array
      summary: Gets units of work for a user
      tags:
      - units
swagger: "2.0"
