@host = http://localhost:8000
@apiPrefix = v1

POST {{host}}/{{apiPrefix}}/units
X-Hackerlog-EditorToken: c918791b-13b8-46d0-ad8f-2b76fbc03ca8

{
  "editor_type": "vscode",
  "project_name": "web-consumer-app",
  "file_name": "app.js",
  "loc_written": "{{$randomInt 20 400}}",
  "loc_deleted": "{{$randomInt 3 30}}",
  "computer_type": "macbook pro",
  "os": "osx",
  "started_at": "{{$timestamp -52 m}}",
  "stopped_at": "{{$timestamp}}"
}

###

POST {{host}}/{{apiPrefix}}/users

{
  "email": "test@test.com",
  "first_name": "Test",
  "last_name": "Dummy",
  "password": "password",
  "username": "test"
}

###

POST {{host}}/{{apiPrefix}}/auth/login

{
  "email": "test@test.com",
  "password": "password123"
}

###

PUT {{host}}/{{apiPrefix}}/users/2

{
  "title": "The baby was over the hype of it all",
  "body": "Lorem ipsum dolor sit amet consectetur adipiscing elit imperdiet erat tempus dui",
  "excerpt": "Lorem ipsum dolor"
}

###

GET {{host}}/{{apiPrefix}}/core/version?currentVersion=v0.3&os=darwin

###

GET {{host}}/{{apiPrefix}}/core/version?currentVersion=v0.3&os=windows&arch=amd64

###

GET {{host}}/{{apiPrefix}}/core/version?currentVersion=v0.4&os=windows


###
POST {{host}}/{{apiPrefix}}/mailing-list
Content-Type: "application/json"

{
  "email": "deric.cain@gmail.com"
}

###
POST {{host}}/{{apiPrefix}}/auth/password-reset
Content-Type: "application/json"

{
  "email": "deric.cain@gmail.com"
}

###
POST {{host}}/{{apiPrefix}}/auth/reset-password
Content-Type: "application/json"

{
  "email": "deric.cain@gmail.com",
  "token": "Orj1bHDR9LomH9OCRvThcfQmcJgPqE6WeeutVj6rg8wqApHoZvFaqnJC8Vihf2cUFw8yGPKqjhj1cQG8S8XP2o6Yz5qUOgbCbhSwdBbbvNiMIgqM6cPxpl2T",
  "password": "password"
}

###
DELETE {{host}}/{{apiPrefix}}/auth/purge-resets
Content-Type: "application/json"
X-Hackerlog-PurgeToken: punt-smek-tim-pank-pub-drect-hoss-vuk
