@host = http://localhost:8080
@apiPrefix = v1

GET {{host}}/{{apiPrefix}}/posts

###

GET {{host}}/{{apiPrefix}}/posts/7

###

POST {{host}}/{{apiPrefix}}/units
X-Hackerlog-EditorToken: c918791b-13b8-46d0-ad8f-2b76fbc03ca8

{
  "editor_type": "vscode",
  "project_name": "web-consumer-app",
  "file_name": "app.js",
  "loc_written": "{{$randomInt 20 400}}",
  "loc_deleted": "{{$randomInt 3 30}}",
  "computer_type": "macbook pro",
  "os": "osx",
  "started_at": "{{$timestamp -52 m}}",
  "stopped_at": "{{$timestamp}}"
}

###

GET {{host}}/{{apiPrefix}}/users

###

GET {{host}}/{{apiPrefix}}/users/1

###

GET {{host}}/{{apiPrefix}}/users/41dc247f-df46-4885-8c18-400f011894c9

###

POST {{host}}/{{apiPrefix}}/users

{
  "email": "deric.cain1@gmail.com",
  "name": "Deric Cain",
  "password": "password"
}

###

PUT {{host}}/{{apiPrefix}}/users/2

{
  "title": "The baby was over the hype of it all",
  "body": "Lorem ipsum dolor sit amet consectetur adipiscing elit imperdiet erat tempus dui",
  "excerpt": "Lorem ipsum dolor"
}

###

DELETE {{host}}/{{apiPrefix}}/users/1

###

POST {{host}}/{{apiPrefix}}/auth/login

{
  "email": "deric.cain2@gmail.com",
  "password": "password"
}

###

POST {{host}}/{{apiPrefix}}/api/does-not-exists

{
  "nothing": true
}
